# Generated by Django 6.0.5 on 2026-05-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("feat", "feat"),
                            ("fix", "fix"),
                            ("refactor", "refactor"),
                            ("perf", "perf"),
                            ("chore", "chore"),
                            ("hotfix", "hotfix"),
                            ("revert", "revert"),
                            ("merge", "merge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=500)),
                ("reflection", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField()),
                ("branch", models.CharField(default="life/main", max_length=100)),
                ("tag", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("growth", "Growth / Achievement"),
                            ("productive", "Productive / Consistent"),
                            ("emotional", "Emotional / Relational"),
                            ("experiment", "Experimentation / Ideation"),
                            ("difficult", "Difficult / Failure"),
                            ("faith", "Faith"),
                            ("basketball", "Basketball / Physical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20)),
                ("image", models.URLField(blank=True)),
                ("quote", models.TextField(blank=True)),
                ("song", models.CharField(blank=True, max_length=200)),
                ("code_snippet", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="Anonymous", max_length=100),
                ),
                ("message", models.TextField(max_length=280)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("commit", "commit"),
                            ("pr", "pull request"),
                            ("issue", "issue"),
                            ("log", "log"),
                        ],
                        default="commit",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[
                            ("v18", "v18.0.0"),
                            ("v19", "v19.0.0"),
                            ("v20", "v20.0.0"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("is_done", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["version", "order"],
            },
        ),
        migrations.CreateModel(
            name="ScrapbookItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hackathon", "Hackathon"),
                            ("code", "Code"),
                            ("people", "People"),
                            ("basketball", "Basketball"),
                            ("random", "Random"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_taken", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_taken"],
            },
        ),
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="Anonymous", max_length=100),
                ),
                ("wish_text", models.TextField(max_length=500)),
                ("prophecy", models.TextField()),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MapPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pins",
                        to="app.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
